### ISSUE TITLE
Lat, Long coordinate mismatch

### ISSUE THREAD

**Issue by nyanlynntherazi** [theananda/myanmar-covid19-data#5]
Issue initiated by [saitzaw](https://github.com/saitzaw)
Lat, Long values cannot point the real hospital locations

**Comment by htinkyawaye** [comment]
The original http://www.doms.gov.mm/ list is the only consolidated source for hospital lat, long. There must be mismatches for sure. Fixing that would include more laborious tasks matching against other GIS resources. So, I'll close this issue at the moment, mark it for something we could do in less busier times.
