### ISSUE TITLE
Can not remotely parse the Medical Supplies with Location by pandas

### ISSUE THREAD

**Issue by nyanlynntherazi** [theananda/myanmar-covid19-data#6]
Issue initiated by [saitzaw](https://github.com/saitzaw)
ParserError: Error tokenizing data. C error: Expected 1 fields in line 49, saw 2

**Comment by saitzaw** [comment]
This bug is not csv file format. It can solve by raw type, Let use raw type to read the csv from repo. 

`pd.read_csv("https://raw.githubusercontent.com/theananda/myanmar-covid19-data/master/Medical%20Supplies%20with%20Location.csv")`

**Comment by nyanlynntherazi** [comment]
Resolved
