### ISSUE TITLE
Hospital name duplications

### ISSUE THREAD

**Issue by nyanlynntherazi** [theananda/myanmar-covid19-data#7]

**Comment by arky** [comment]
Children Specialist Hospital is repeated twice

https://github.com/theananda/myanmar-covid19-data/blob/master/Hospital%20Names%20in%20English%20and%20Burmese.csv#L68

https://github.com/theananda/myanmar-covid19-data/blob/master/Hospital%20Names%20in%20English%20and%20Burmese.csv#L73

**Comment by nyanlynntherazi** [comment]
They are different hospitals from different location so updated the missing locations. Thank you so much for reporting the issue.

**Comment by arky** [comment]
Thanks @nyanlynntherazi 
Could you please help close https://github.com/theananda/myanmar-covid19-data/issues/25
